/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nbodysimulation.display.barneshut;

import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JFrame;
import nbodysimulation.algorithm.BarnesHut;

/**
 *
 * @author Sely
 */
public class BarnesHutPanel extends javax.swing.JPanel {

    /**
     * Creates new form BruteForcePanel
     */
    BarnesHut bf;

    public BarnesHutPanel() {
        initComponents();

        bf = new BarnesHut(100);
    }

    public void startAnimation(int noOfBodies) {
        bf.startthebodies(noOfBodies);
        bf.shouldrun = true;
        repaint();
    }

    @Override
    public void paintComponent(Graphics g) {
        // Originally the origin is in the top right. Put 
        super.paintComponent(g);
        
        //Centers the action
        g.translate(this.getWidth()/2, this.getHeight()/2);
        //g.translate(250, 250);
        //check if drawing has to be stoped
        if (bf.shouldrun) {
            for (int i = 0; i < bf.N; i++) {
                g.setColor(bf.bodies[i].color);
                g.fillOval((int) Math.round(bf.bodies[i].rx * 250 / 1e18),
                        (int) Math.round(bf.bodies[i].ry * 250 / 1e18), 8, 8);
            }
            // go through the Brute Force algorithm (see the function below)
            bf.addforces(bf.N);

            repaint();
        }        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public static void main(String[] args) {
        javax.swing.SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                final BarnesHutPanel bfp = new BarnesHutPanel();
                final ControlPanel cp = new ControlPanel();

                JFrame jFrame = new JFrame();
                jFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

                jFrame.add(bfp, BorderLayout.CENTER);
                jFrame.add(cp, BorderLayout.PAGE_END);

                cp.startButton.addMouseListener(new MouseAdapter() {

                    @Override
                    public void mouseClicked(MouseEvent e) {
                        int noOfBodies = Integer.parseInt(cp.noOfBodiesText.getText().trim());
                        bfp.startAnimation(noOfBodies);
                    }

                });
                
                //pack frame (size JFrame to match preferred sizes of added components and set visible
                jFrame.pack();
                jFrame.setVisible(true);

            }
        });
    }

}
